org: madang
app: tweetify-lambda
service: tweetify-lambda

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-plugin-typescript
